services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=ceelya'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=ceelya_user'
    ports:
      - '5432:5432'
    volumes:
      - ceelya-data:/var/lib/postgresql/data

volumes:
  ceelya-data: